### ISSUE TITLE
New release for PR #10?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [hypesystem/showandtell.js#11]
Hi there, 

i would be useful to have a new release that includes PR #10.

This way i could use this repo in my project instead of the forked one.

**Comment by ViRuSTriNiTy** [comment]
*Bump*

**Comment by hypesystem** [comment]
Now that #12 has been merged, I will create a release.

**Comment by hypesystem** [comment]
The release is out now: https://github.com/hypesystem/showandtell.js/releases/tag/2.0.0

Thank you for the contributions and patience :smile:

**Comment by ViRuSTriNiTy** [comment]
Awesome.
