### ISSUE TITLE
Hiding multiple elements with a single selector does NOT fire showandtell.hide

### ISSUE THREAD

**Issue by pbiron** [hypesystem/showandtell.js#14]
First, let me say THANK YOU for this plugin, using it has greatly simplified some code that I writing for a client's site!!

That said, I've discovered a (possible) problem (I don't know whether I'd call it a bug or not):  `showandtell.hide` is **not** triggered when multiple elements are hidden with a single selector.

For example:

```javascript
$( '#foo, #bar' ).hide(); // does not trigger showandtell.hide
```

Instead, I've found that I need to use either:

```javascript
$( '#foo' ).hide();
$( '#bar' ).hide();
```

which is klunky, or

```javascript
$( '#foo, #bar' ).each( function() {
      $( this ).hide();
} );
```
which is cumbersome.

You can see the problem in action at [https://jsfiddle.net/pbiron/747jxuc1/](https://jsfiddle.net/pbiron/747jxuc1/).

That jsfiddle is pared down from one part of the client site I'm building, and there are detailed instructions for how to surface the problem with `$( '#foo, #bar' ).hide();`, and how both `$( '#foo' ).hide(); $( '#bar' ).hide();` and `$( '#foo, #bar' ).each( function() { $( this ).hide(); } );` work.

**Comment by hypesystem** [comment]
Hey!

Thanks for filing this issue! It's been a long time since I last touched this library, but if you're willing to try and write the code to fix the issue, I'll give you guidance as best I can. Would you be interested in that?

If so, start a pull request, and we can talk through the changes there.

I think the first step should be adding a test case for the failing case you are reporting. And then add code that fixes it :smile:

**Comment by pbiron** [comment]
sure...I'll have to bone up on how to write JUnit tests first.  Look for a PR in the next few days.

**Comment by hypesystem** [comment]
Great, thanks!

**Comment by pbiron** [comment]
I've looked into what is causing such "multiple selectors" to fail and have a fix that works for my case, but I'll have to run all your existing unit tests with the fix to make sure that my fix doesn't break other things.

The problem has to with `checkIfElementWasHidden()` returning a single boolean value, whereas it needs to return an array of boolean values...and then `hide.post()` and `show.post()` need to iterate over `this` with the appropriate value from the `elementWasHidden` array.

That is, the fix looks something like (without worrying about efficiency):

```javascript
function checkIfElementWasHidden() {
	return $( this ).map( function() { return $( this ).is( ':hidden' ); } ).toArray();
}
...
proxy$Functions( {
	hide: {
		post: function( result, elementWasHidden, old_args ) {
			$( this ).each( function( idx ) {
				if ( ! elementWasHidden[idx] ) { 
					this.triggerHandler( 'showandtell.hide' );
				}
			} );
		} );
	}
	show: {
		post: function( result, elementWasHidden, old_args ) {
			$( this ).each( function( idx ) {
				if ( elementWasHidden[idx] ) { 
					this.triggerHandler( 'showandtell.show' );
				}
			} );
		} );
	}
} );
```

**Comment by hypesystem** [comment]
Seems like a decent solution! Does this work with selectors of a single element (e.g. `$("#foo")`), too?

I think maybe the code would be more readable if you move to a slightly more functional style with a call to a filter-function rather than an if-statement inside the each, here an example for how the body of hide.post could look:

```js
$(this)
    .filter(function(idx) { return !elementWasHidden[idx]; })
    .each(function() { this.triggerHandler('showandtell.hide'); });
```

**Comment by pbiron** [comment]
> Seems like a decent solution! Does this work with selectors of a single element (e.g. $("#foo")), too?

It does in the "informal" tests I've run.  But I haven't tried it with all the existing unit tests.

> I think maybe the code would be more readable if you move to a slightly more functional style with a call to a filter-function rather than an if-statement inside the each

Agreed!

**Comment by hypesystem** [comment]
Cool! Throw me a PR and we can work on getting the tests running together
