### ISSUE TITLE
add a version #

### ISSUE THREAD

**Issue by pbiron** [hypesystem/showandtell.js#16]
Can I suggest that you add a verison # (as a comment in `showandtell.js`)?

I'm using it in a WordPress plugin and it would help me if there were a specific version # for the file.

**Comment by hypesystem** [comment]
Hi!

I'm not sure exactly what you mean. There is a version number included in the file name if you download a release from here: https://github.com/hypesystem/showandtell.js/releases

Otherwise, you can use the npm package, which uses npm's versioning: http://npmjs.com/package/jquery.showandtell.js

What is it that a WordPress plugin would need, and why?

**Comment by pbiron** [comment]
I was thinking of adding a comment to the header of the file, such as
```
/**
 * Version: x.y.z
 */
```
In a WordPress plugin, to tell WordPress to generate an appropriate `<script>` element, one calls  [wp_enqueue_script()](https://developer.wordpress.org/reference/functions/wp_enqueue_script/), as in:
```
wp_enqueue_script( 'showandtell', '/path-to-plugin/js/showandtell.js', array( 'jquery' ), 'x.y.z' );
```

results in the following HTML being generated:
```
<script type='text/javascript' src='http://host/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://host/wp-content/path-to-plugin/js/showandtell.js?ver=x.y.z'></script>
```
WordPress adds the `?ver=x.y.z` to the URL in `script/@src` to help with "cache busting", that is, to help browsers/proxies know when their cache is out of date.

And I just need and I just needed to know what value to pass in that final parameter to `wp_enqueue_script()`.

I hadn't looked at the releases, I had just been using the .js file from the master branch of the repo.  The verison # in the filename is good enough for my purposes.

**Comment by pbiron** [comment]
Also, I'd suggest you add the URL of this repo to the header comment (in both the minified and un-minified version) so that when folks like me include it in a project you get appropriate credit :-)

**Comment by hypesystem** [comment]
Cool, thanks. Glad the releases work for you :smile:

I'm not sure I need the credit for the lib, and it's openly licensed, so people are free to just copy it. If they have problems, I hope they will google the script name and get in touch :smile:

**Comment by pbiron** [comment]
OK, thanx for considering this request.
